// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeradaaxmqzyvxvmahlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlcmFkYWF4bXF6eXZ4dm1haGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExOTMwNTAsImV4cCI6MjA4Njc2OTA1MH0.w4oKGySELbrqXZkw4wcBwhLUXjN66UtcxaV6CHmhdys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});